remote_theme: jekyll-theme-midnight
title: FileFlows Documentation
description: Documentation for FileFlows

collections:
  pages:
    output: true
  plugins:
    output: true
    nodes:
      output: true
  guides:
    output: true