title: FileFlows Documentation
description: Documentation for FileFlows
remote_theme: rundocs/jekyll-rtd-theme

include:
 - _pages
 - _plugins
 - _guides
 
collections:
  pages:
    output: true
  plugins:
    output: true
    nodes:
      output: true
  guides:
    output: true