title: FileFlows Documentation
description: Documentation for FileFlows
plugins:
  - jekyll-toc

collections:
  pages:
    output: true
  plugins:
    output: true
    nodes:
      output: true
  guides:
    output: true