title: FileFlows Documentation
description: Documentation for FileFlows
#remote_theme: chrisrhymes/bulma-clean-theme
#remote_theme: rundocs/jekyll-rtd-theme
remote_theme: pmarsceill/just-the-docs


include:
 - _pages
 - _plugins
 - _guides

collections:
  pages:
    output: true
  plugins:
    output: true
    nodes:
      output: true
  guides:
    output: true